### ISSUE TITLE
Split schema for source_types

### ISSUE THREAD

**Issue by rvsia** [ManageIQ/sources-api#88]
We need to come up with a new system for schemas stored in DB, because in `application_types`, there are `supported_authentication_types` which cannot be used to use the right authentication type, because there isn't anything like `authentication_type`.

I propose something like:

```rb
# application_types.rb

...
supported_authentication_types: {
  "ansible_tower" => ["username_password"],
}
...

# source_types.rb

ansible_tower_json_schema = {
  :authentication => {
    :title => "Configure AnsibleTower Authentication"
    :username_password => {
      :fields => {
        {:component => "text-field", :name => "authentication.authtype", :type => "hidden", :initialValue => "username_password"},
        {:component => "text-field", :name => "authentication.username", :label => "User name"},
        {:component => "text-field", :name => "authentication.password", :label => "Secret Key", :type => "password"}
      }
    }
  },
  :endpoint => {
    :title => "Configure AnsibleTower Endpoint",
    :fields => {
      {:component => "text-field", :name => "endpoint.role", :type => "hidden", :initialValue => "ansible"}, # FIXME: Find the correct value.
      {:component => "text-field", :name => "url", :label => "URL", :validate => [{:type => "url-validator"}]},
      {:component => "checkbox", :name => "endpoint.verify_ssl", :label => "Verify SSL"},
      {:component => "text-field", :name => "endpoint.certificate_authority", :label => "Certificate Authority", :condition => {:when => "endpoint.verify_ssl", :is => true}},
    }
  }
}

update_or_create(:name => "ansible_tower", :product_name => "Ansible Tower", :vendor => "Red Hat", :schema => ansible_tower_json_schema)
```

There are several possible questions/modifications I have:

1) Default authentication types (i.e. `:default => ...` ) Would be something like this required or would every application have always the supported_auth type provided?

2) Custom titles for each type (add `:title` to each type hash), do we need to have different titles for each type `Configure Amazon ARN`, `Configure Secret Key`?

3) For better usability I divided endpoints/authentications to two steps. I am not sure if we want this (UX reasons, backend reasons...) but it would be much better for building of the final form.

4) Will be there different types of endpoints?

5) I18n - We should start to think how we will provide localized texts.

   a) On API side - I have no idea

   b) On frontend - instead of hardcoded labels (i.e.: `:label => "URL"`) send ID (`:label_id => 'sources.url'`) (or both to support applications without a I18n solution) and the frontend will pre-process schemas and inject the right labels there.

@agrare @gtanzillo

**Comment by agrare** [comment]
@rvsia makes sense that the authentication type should be more formalized.  I like your example above but we should probably have a title for the authentication type so that e.g. "Username/Password" or "ARN" could be shown on the UI to the user.

Could you also show an example of a Cost Management case where there are two types of authentications supported?

**Comment by rvsia** [comment]
@agrare 

Ad Title) As I stated in my question 2, we could add title for each authentication type
Ad Cost Management )

```rb
# source_types.rb

amazon_json_schema = {
  :authentication => {
    :title => "Configure AWS", # Fallback
    :access_key_secret_key => {
      :title => "Configure AWS secret identity", # custom title
      :fields => [
        {:component => "text-field", :name => "authentication.authtype", :type => "hidden", :initialValue => "access_key_secret_key"},
        {:component => "text-field", :name => "authentication.username", :label => "Access Key"},
        {:component => "text-field", :name => "authentication.password", :label => "Secret Key", :type => "password"}
      ]
    }
    :arn => {
      :title => "Configure AWS ARN credentials",
      :fields => [
        {:component => "text-field", :name => "authentication.authtype", :type => "hidden", :initialValue => "arn"},
        {:component => "text-field", :name => "authentication.arn", :label => "ARN"},
      ]
    }
  }
  :endpoint => {
    # no title needed, this step would not be shown in UI, as it is only hidden field
    :hidden => true, # simple flag would make it easier for UI, but is not required
    :fields => [
          {:component => "text-field", :name => "endpoint.role", :type => "hidden", :initialValue => "aws"},
    ]
  }
}
```

**Comment by agrare** [comment]
:+1: go ahead and update it for what you need @rvsia
